In [2]:
# Pytorch에서는 텐서를 사용하여 모델의 입력과 출력, 그리고 매개변수를 부호화 한다.
# Numpy의 ndarray와 매우 유사
import torch
import numpy as np

In [4]:
# Tensor 초기화
data = [[1,2],[3,4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [5]:
# Numpy 배열로부터 생성하기
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

In [6]:
# 다른 텐서로부터 생성하기:
x_ones = torch.ones_like(x_data)
print(x_ones)

x_rand = torch.rand_like(x_data,dtype=torch.float)
print(x_rand)

tensor([[1, 1],
        [1, 1]])
tensor([[0.6037, 0.2662],
        [0.3658, 0.3084]])


In [7]:
# 무작위 뜨는 상수값을 사용하기
shape=(2,3)
rand_tensor = torch.rand(shape)
print(rand_tensor)

ones_tensor = torch.ones(shape)
print(ones_tensor)

zero_tensor = torch.zeros(shape)
print(zero_tensor)

tensor([[0.3142, 0.7115, 0.2687],
        [0.6506, 0.9118, 0.1419]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [8]:
# 텐서의 속성
# 텐서의 속성은 텐서의 shape, datatype 및 어느 장치에 저장되는지를 나타냅니다.
tensor = torch.rand(3,4)

print(tensor.shape)
print(tensor.dtype)
print(tensor.device)

torch.Size([3, 4])
torch.float32
cpu


In [10]:
# 텐서 연산
# GPU를 이용하면 병렬 연산이 빠르게 가능
# Notebook Settings에서 GPU를 할당할 수 있다.

# GPU가 존재하면 텐서를 이동
if torch.cuda.is_available():
    tensor = tensor.to('cuda')
    print(f"Device tensor is stored on: {tensor.device}")

Device tensor is stored on: cuda:0


In [11]:
# Pytorch API -> Numpu API랑 비슷
tensor = torch.ones(4,4)
tensor[:,1] = 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [13]:
# Tensor 합치기
t1 = torch.cat([tensor,tensor,tensor], dim=1)
print(t1)

t2 = torch.cat([tensor,tensor,tensor], dim=0)
print(t2)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [16]:
# Tensor 곱하기 

# element-wise product(요소별 곱)
print(tensor.mul(tensor))

# 다른 문법
print(tensor*tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [19]:
print(tensor.matmul(tensor.T))
print(tensor @ tensor.T)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


In [21]:
# 바꿔치기(in-place) 연산
print(tensor, "\n")
tensor.add_(5)
print(tensor)
# in-place 연산 -> 메모리를 일부 절약하지만, 기록이 즉시 삭제됨
# 도함수 계산에 문제가 발생할 수 있어서, 사용을 권장하지 않는다고 함!

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]]) 

tensor([[11., 10., 11., 11.],
        [11., 10., 11., 11.],
        [11., 10., 11., 11.],
        [11., 10., 11., 11.]])


In [23]:
# Numpy 변환
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n:{n}")

t: tensor([1., 1., 1., 1., 1.])
n:[1. 1. 1. 1. 1.]


In [24]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [28]:
# Numpy배열을 텐서로 변환하기
n = np.ones(5)
t = torch.from_numpy(n)

print('======================')
print(f"t: {t}")
print(f"n: {n}")

print('======================')
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")


t: tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
n: [1. 1. 1. 1. 1.]
t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
